version: '3'
services:
  webapp:
    build: .
    volumes:
      - .:/webapp
    ports:
      - 3000:3000
    container_name: webapp
    links:
      - db
    command: sh /webapp/scripts/startup.sh
    env_file: .env
    stdin_open: true
    tty: true

  db:
    image: postgres:10.0
    container_name: db
    env_file: .env

