version: '3'
services:
  web:
    build: .
    volumes:
      - .:/web
    ports:
      - 3000:3000
    container_name: web
    links:
      - dbp
    command: sh /web/scripts/startup.sh
    env_file: .env
    stdin_open: true
    tty: true

  dbp:
    image: postgres:10.0
    container_name: dbp
    env_file: .env

